# Generated by Django 4.2.3 on 2023-07-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_location_created_at_professional_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='location',
            name='venue',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='event_name',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='professional',
            name='bio',
            field=models.CharField(max_length=500),
        ),
    ]
