# Generated by Django 4.2.3 on 2023-07-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_location_bio_remove_location_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='link',
            field=models.URLField(default=1, max_length=300),
        ),
    ]
