# Generated by Django 4.2.3 on 2023-07-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='img',
            field=models.CharField(max_length=800),
        ),
    ]
