# Generated by Django 4.2.3 on 2023-07-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_professional_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='link',
        ),
    ]
